// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUq4xGzx7O9iIZ85VDSYW_zks4jHcuLQ',
    appId: '1:18862066015:web:7761343252904797d80eea',
    messagingSenderId: '18862066015',
    projectId: 'playersconnect-3bc56',
    authDomain: 'playersconnect-3bc56.firebaseapp.com',
    storageBucket: 'playersconnect-3bc56.firebasestorage.app',
    measurementId: 'G-9QHNNVVV2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVtbdgyDopxNPlU3T85jg7kAK3J56UXc',
    appId: '1:18862066015:android:9328f597192b72e0d80eea',
    messagingSenderId: '18862066015',
    projectId: 'playersconnect-3bc56',
    storageBucket: 'playersconnect-3bc56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zgOdCqUBv94ygVZmAFlmFJ44-o35Z84',
    appId: '1:18862066015:ios:379930f78790c8c3d80eea',
    messagingSenderId: '18862066015',
    projectId: 'playersconnect-3bc56',
    storageBucket: 'playersconnect-3bc56.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zgOdCqUBv94ygVZmAFlmFJ44-o35Z84',
    appId: '1:18862066015:ios:379930f78790c8c3d80eea',
    messagingSenderId: '18862066015',
    projectId: 'playersconnect-3bc56',
    storageBucket: 'playersconnect-3bc56.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrUq4xGzx7O9iIZ85VDSYW_zks4jHcuLQ',
    appId: '1:18862066015:web:30a005ffc9368c80d80eea',
    messagingSenderId: '18862066015',
    projectId: 'playersconnect-3bc56',
    authDomain: 'playersconnect-3bc56.firebaseapp.com',
    storageBucket: 'playersconnect-3bc56.firebasestorage.app',
    measurementId: 'G-CX0TPVRZQC',
  );
}
